export const STATUS_RESPONSE_API = {
  SUCCESS_OK: 200,
  SUCCESS_CREATED: 201,
  SUCCESS_NO_CONTENT: 204,
  CLIENT_ERROR_BAD_REQUEST: 400,
  CLIENT_ERROR_UNAUTHORIZED: 401,
  CLIENT_ERROR_FORBIDDEN: 403,
  CLIENT_ERROR_NOT_FOUND: 404,
  SERVER_ERROR_INTERNAL_ERROR: 500
}
